esphome:
  name: $devicename

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

<<: !include ../common/common.yaml
<<: !include ../common/bluetooth_proxy.yaml

sensor:
  - platform: pulse_counter
    pin: GPIO36
    name: ${upper_devicename}
    id: "geiger_counter"
    unit_of_measurement: 'CPM'
    on_raw_value:
      - sensor.template.publish:
          id: radiation_level
          state: !lambda 'return x / 153.8;'
  - platform: template
    name: "Radiation Level"
    id: "radiation_level"
    unit_of_measurement: 'µSv/h'
    icon: mdi:radioactive
    accuracy_decimals: 5
  - <<: !include wifi_signal.yaml

binary_sensor:
  - platform: template
    device_class: safety
    name: "Radiation Warning"
    lambda: |-
      if (id(geiger_counter).state > 100) {
        // High Count.
        return true;
      } else {
        // Normal Count.
        return false;
      }

text_sensor:
  - <<: !include wifi_info.yaml

# Enable Home Assistant API
api:
