esphome:
  name: $devicename

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

<<: !include common/common.yaml
<<: !include common/bluetooth_proxy.yaml

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: id_mhz19
    co2:
      name: ${upper_devicename} CO2 ppm
      on_value_range:
        - below: ${co2_level_1}
          then:
            - switch.turn_on: green_led
            - switch.turn_off: red_led
        - above: ${co2_level_1}
          then:
            - switch.turn_on: green_led
            - switch.turn_on: red_led
        - above: ${co2_level_2}
          then:
            - switch.turn_off: green_led
            - switch.turn_on: red_led
    temperature:
      name: ${upper_devicename} Temperature
    update_interval: 60s
    automatic_baseline_calibration: false
  - <<: !include sensors/wifi_signal.yaml

text_sensor:
  - <<: !include sensors/wifi_info.yaml

switch:
  - platform: gpio
    pin: GPIO14
    id: red_led
    name: ${upper_devicename} LED Red
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO16
    id: green_led
    name: ${upper_devicename} LED Green
    restore_mode: ALWAYS_OFF
  - platform: template
    disabled_by_default: true
    name: ${upper_devicename} Calibrate
    optimistic: true
    on_turn_on:
      mhz19.calibrate_zero: id_mhz19

api:
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: id_mhz19
