esphome:
  name: $devicename

<<: !include common/common.yaml

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: ${upper_devicename} PM 2.5
  - <<: !include sensors/wifi_signal.yaml

text_sensor:
  - <<: !include sensors/wifi_info.yaml

# Enable Home Assistant API
api: